### ISSUE TITLE
Lutris forbidden url error

### ISSUE THREAD

**Issue by Blasphemy029** [eskay993/gamefiles#34]
> **Details:**

- Which game are you trying to install?
Resident Evil

- What platform/distro are you trying it on (e.g. Steam Deck)?
Steam Deck

**Issue Description:**
_Please provide details of what steps you followed when the issue occurred:_
Forbidden url error when trying to install with lutirs. Using the .yaml install script, after selecting directory and creating steam short cut. Lutis encounters 403 Client error: Forbidden url.

**Error Log:**

```

_If you got an error message, please paste the full log here (not just the error code)._


```

403 Client Error: Forbidden for url: https://www.moddb.com/downloads/re1-classic-rebirth-high-quality-video-pack

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 147, in raise_for_status
    text = response.json()
           ^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/installer/installer.py", line 165, in prepare_game_files
    file.set_url(ModDB().transform_url(file.url))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/moddb.py", line 51, in transform_url
    + self._autoselect_moddb_mirror(self._get_html_and_resolve_mirrors_list(moddb_permalink_url))._url
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/moddb.py", line 70, in _get_html_and_resolve_mirrors_list
    moddb_obj = self.parse(moddb_permalink_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/moddb/base.py", line 106, in parse_page
    html = get_page(url)
           ^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 241, in get_page
    r = request(requests.Request("GET", url, params=params))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/pyrate_limiter/limit_context_decorator.py", line 54, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 213, in request
    raise_for_status(r)

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 154, in raise_for_status
    response.raise_for_status()

  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.moddb.com/downloads/re1-classic-rebirth-high-quality-video-pack

**Comment by eskay993** [comment]
Thanks for flagging. Seems to be an issue with Lutris' moddb integration. Not see any reports on the Lutris repo yet.

It should hopefully be fixed by Lutris/moddb at some point. In the meantime, I created a version that disables auto downloading from moddb.

https://github.com/eskay993/gamefiles/blob/main/resident-evil/scripts/resident-evil-gog-manual.zip

You will need to download the movie pack yourself from [RE1 Classic REbirth High Quality video pack](https://www.moddb.com/downloads/re1-classic-rebirth-high-quality-video-pack), then add it to the script when prompted.

If it the moddb issue doesn't get fixed in the next few days, I will updates all the RE scripts.

**Comment by Blasphemy029** [comment]
Thanks for the quick response. This worked perfectly.
