### ISSUE TITLE
Silent hill 3 cant install

### ISSUE THREAD

**Issue by Mr-nobody7** [eskay993/gamefiles#37]
**Details:**

- Which game are you trying to install?
silent hill 3

- What platform/distro are you trying it on (e.g. Steam Deck)?
steam deck

**Issue Description:**

_Please provide details of what steps you followed when the issue occurred:_
when trying to install. its trying to access a website but cant access it 

**Error Log:**

_If you got an error message, please paste the full log here (not just the error code)._
403 Client Error: Forbidden for url: https://www.moddb.com/mods/silent-hill-3-audio-enhancement-pack/downloads/silent-hill-3-audio-enhancement-pack-version-206

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 147, in raise_for_status
    text = response.json()
           ^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/installer/installer.py", line 165, in prepare_game_files
    file.set_url(ModDB().transform_url(file.url))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/moddb.py", line 51, in transform_url
    + self._autoselect_moddb_mirror(self._get_html_and_resolve_mirrors_list(moddb_permalink_url))._url
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/moddb.py", line 70, in _get_html_and_resolve_mirrors_list
    moddb_obj = self.parse(moddb_permalink_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/moddb/base.py", line 106, in parse_page
    html = get_page(url)
           ^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 241, in get_page
    r = request(requests.Request("GET", url, params=params))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/pyrate_limiter/limit_context_decorator.py", line 54, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 213, in request
    raise_for_status(r)

  File "/app/lib/python3.11/site-packages/moddb/utils.py", line 154, in raise_for_status
    response.raise_for_status()

  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.moddb.com/mods/silent-hill-3-audio-enhancement-pack/downloads/silent-hill-3-audio-enhancement-pack-version-206
```


```

**Comment by eskay993** [comment]
Unfortunately there is an issue with Lutris downloading from moddb at the moment. I've flagged it to the Lutris team. In the meantime try this workaround script...

https://github.com/eskay993/gamefiles/issues/34#issuecomment-2453418263

**Comment by Mr-nobody7** [comment]
will this work for silent hill 3? this looks for resident evil

**Comment by eskay993** [comment]
Oh sorry, got confused between games as they are both moddb errors.

I would need to create a new script for SH3, to fix the modbd issue but if I remember SH3 script has other issues that I haven't had time to look into.

My general recommendation for people is to emulate the PS2 version of SH3. It's a bit of a cat and mouse game with the mod tools that are needed on PC and they keep changing and breaking things in the script.

I might have time to look at it this weekend, but honestly just emulate it for now. That what I did my last play through.
